export const ui = Object.fromEntries(
    [
      "projectInfo","projectDialog","projectInfoTitle","projectInfoClose","projectSource","projectContents","projectFileName","projectCopyPath","projectRuntime","projectLibraries","projectIssue","projectExportNote","projectInfoError","circuitNavigator","collapseNavigator","collapseInspector","inspectorResize","connectionsSummary","connectionList","simulationOptions","connectionChooseModel",
      "agentMaterials","materialAttachments","materialsDialog","materialsTitle","materialsAdd","materialsClose","materialsError","materialsUndoBar","materialsUndoText","materialsUndo","materialsSearch","materialsActive","materialsRemoved","materialsList","materialsDetailHead","materialsName","materialsMeta","materialsRemove","materialsPreview","materialsFooter","materialPrev","materialNext","materialPage","materialImageMode","materialTextMode","materialQuote","materialsHint",
      "editInterface","interfaceDialog","interfaceTitle","interfaceScope","interfaceClose","interfaceError","interfaceAddRect","interfaceAddText","interfaceUndo","interfaceFit","interfaceCanvas","interfaceArtwork","interfaceProperties","interfaceAddPort","interfacePortList","interfaceImpact","interfaceDraftStatus","interfacePreview","interfaceApply",
      "comparisonNative",
      "candidateEvidenceDialog","candidateEvidenceTitle","evidenceBack","closeCandidateEvidence","evidenceModule","evidenceVectors","evidenceTrace","evidenceResults",
      "comparisonDialog","comparisonTitle","comparisonKind","comparisonDownload","comparisonEvidence","comparisonPrimary","comparisonClose","comparisonError","comparisonModule","comparisonMode","comparisonBefore","comparisonAfter","comparisonSummary","comparisonReload","comparisonScope","comparisonFilters","comparisonSearch","comparisonRows","comparisonZoomOut","comparisonZoom","comparisonZoomIn","comparisonFit","comparisonImageStatus","comparisonStage","comparisonSheet","comparisonImage","comparisonOverlay","comparisonDetailImage","comparisonMarks","comparisonDetails","comparisonLocate",
      "appShell", "workbench", "inspectorSection", "railResize", "reviewResize", "clearObjectSelection", "clearComposerContext", "conversationLatest", "draftError", "draftErrorText", "draftRetry", "draftCopy", "composerOptions",
      "findObject", "finderDialog", "finderInput", "finderClose", "finderScope", "finderStatus", "finderResults",
      "openButton",
      "saveButton", "undoButton", "saveStatus", "saveDialog", "saveFileName", "cancelSave", "confirmSave",
      "saveActionError",  
      "pendingChanges", "pendingChangesButton", "projectHistoryButton", "projectHistory", "exportProject",
            
           
      "emptyOpenButton",
      "fileInput",
      "staleBanner", "connectionWarning",
      "reloadRevisionButton",
      "workspaceName",
      "circuitCount",
      "circuitSearch",
      "circuitList",
      "canvasStage",
      "canvasStatus",
      "momentCapture","momentOpen","momentAttachments","momentDialog","momentClose","momentList","momentViewer","momentAttach",
      "simulationDock", "simulationStatus", "simulationMenuButton", "simulationMenu", "simulationOwner", "simulationSettingsClose", "simulationSettingsForm", "simulationSettingsCancel", "simulationSettingsApply", "simulationSettingsError", "simulationStart", "simulationPlay", "simulationTick",
      "simulationReset", "simulationStop", "simulationReturn", "simulationWatches", "simulationError",
      "simulationStep", "simulationFrequency", "simulationSettings", "simulationAutomatic", "simulationRate",
      "pokeTool", "memoryPanel", "memoryOwner", "memoryKind", "memoryClose", "memoryJump", "memoryAddress",
      "memoryGeometry", "memoryPrev", "memoryNext", "memoryRefresh", "memoryContent", "memorySelection", "memoryState", "memoryError",
      "circuitCanvas",
      "gridPlane",
      "nativeArtwork", "runtimeLayer", "detailLayer", "renderStatus", "circuitBreadcrumbs", "definitionContext", "currentCircuitName", "documentKind", "circuitBack", 
      "objectInspector", "candidateList",   
         
        
        
          
          
         
      "wireLayer",
      "componentLayer",
      "interactionLayer",
      "emptyState",
      "emptyHint",
      "selectionDock",
      "selectionSummary",
      "selectionRevision",
      "copyReferenceButton",
      "questionInput",
      "askButton",
      "interruptButton",
      "selectTool",
      "panTool",
      "zoomOutButton",
      "zoomInButton",
      "zoomReadout",
      "fitButton",
      "deleteSelectionButton",
      "evidenceTab",
      "agentTab",
      "agentTabLight",
      "agentSettings","connectionDialog","connectionClose","connectionModel","connectionPreference","connectionError","modelSearch",
      "composerPreferences", "agentMode", "agentModel", "agentEffort", "modeMenu", "modeOptions", "modeError", "effortMenu", "effortOptions", "effortError", "attachMaterials",  
      "proposalTab",
      "proposalCount",
      "evidencePane",
      "agentPane",
      "agentStatusLight",
      "agentStatusText",
      "agentNotice", "agentNoticeTitle", "agentNoticeText", "agentNoticeDetails", "agentReconnect", "agentReviewChanges",
      "modelDialog", "modelClose", "modelConnection", "modelConnectionStatus", "modelReconnect", "modelChoice", "modelDescription",   "modelRefresh",  "modelError", "modelLoading", "modelBusy", "connectionHelp", "connectionLogout",
      "agentTimeline",
      "agentEmpty",
      "conversationStarters",
      "proposalPane",
      "evidenceTitle",
      "proposalContent",
      "toggleCircuits",
      "toggleReview",
      "circuitRail",
      "reviewPanel",
      
      "toast",
    ].map((id) => [id, document.getElementById(id)]),
  );
